apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-master1
  namespace: odf-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-master1
  template:
    metadata:
      labels:
        app: nginx-master1
    spec:
      nodeName: master1
      containers:
        - name: nginx
          image: registry.k8s.io/nginx-slim:0.26
          ports:
            - containerPort: 80
          volumeMounts:
            - name: shared-data
              mountPath: /shared
      volumes:
        - name: shared-data
          persistentVolumeClaim:
            claimName: cephfs-rwx-pvc
