apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cephfs-rwx-pvc
  namespace: odf-demo
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: ocs-storagecluster-cephfs
