apiVersion: apps/v1
kind: Deployment
metadata:
  name: tester-rwx
  namespace: odf-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tester-rwx
  template:
    metadata:
      labels:
        app: tester-rwx
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchLabels:
                  app: tester-rwx
              topologyKey: kubernetes.io/hostname
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: tester
          image: registry.access.redhat.com/ubi9/ubi-minimal
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
          command:
            - /bin/sh
            - -c
            - sleep infinity
          volumeMounts:
            - name: shared-data
              mountPath: /shared
      volumes:
        - name: shared-data
          persistentVolumeClaim:
            claimName: cephfs-rwx-pvc
