apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: timescaledb
  namespace: odf-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: timescaledb
  serviceName: timescaledb
  template:
    metadata:
      labels:
        app: timescaledb
    spec:
      securityContext:
        fsGroup: 1000850000
      containers:
        - name: timescaledb
          image: image-registry.openshift-image-registry.svc:5000/odf-demo/timescaledb:2.17.2
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: timescaledb-secret
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_DB
              value: postgres
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          ports:
            - containerPort: 5432
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
            limits:
              cpu: 1
              memory: 1Gi
          livenessProbe:
            tcpSocket:
              port: 5432
            initialDelaySeconds: 30
          readinessProbe:
            tcpSocket:
              port: 5432
            initialDelaySeconds: 10
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 20Gi
        storageClassName: ocs-storagecluster-ceph-rbd
